version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.3

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      # Checkout source code
      - checkout

      # Restore NuGet packages
      - run:
          name: Restore Dependencies
          command: |
            dotnet restore src/SampleApi/SampleApi.csproj

      # Build Application
      - run:
          name: Build Application
          command: |
            dotnet build src/SampleApi/SampleApi.csproj --no-restore

      # Run Unit Tests
      - run:
          name: Run Unit Tests
          command: |
            dotnet test tests/SampleApi.Tests/SampleApi.Tests.csproj

      # Install Docker CLI
      - run:
          name: Install Docker CLI
          command: |
            apt-get update
            apt-get install -y docker.io
            docker --version

      # Enable Remote Docker
      - setup_remote_docker

      # Build Docker Image
      - run:
          name: Docker Build
          command: |
            docker build -t sampleapi:v1 .

      # Install Trivy
      - run:
          name: Install Trivy
          command: |
            apt-get update
            apt-get install -y wget gnupg lsb-release unzip curl

            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
              gpg --dearmor -o /usr/share/keyrings/trivy.gpg

            echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" \
            > /etc/apt/sources.list.d/trivy.list

            apt-get update
            apt-get install -y trivy

      # Scan Docker Image
      - run:
          name: Trivy Security Scan
          command: |
            trivy image --severity HIGH,CRITICAL sampleapi:v1

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -q awscliv2.zip
            ./aws/install
            aws --version

      # Login to Amazon ECR
      - aws-ecr/ecr-login:
          region: AWS_DEFAULT_REGION
          account-id: AWS_ACCOUNT_ID

      # Tag Docker Image
      - run:
          name: Tag Docker Image
          command: |
            docker tag sampleapi:v1 \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sampleapi:v1

      # Push Docker Image
      - run:
          name: Push Docker Image to Amazon ECR
          command: |
            docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sampleapi:v1

workflows:
  version: 2

  ci_pipeline:
    jobs:
      - build
