version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - checkout

      - run:
          name: Restore Dependencies
          command: dotnet restore src/SampleApi/SampleApi.csproj

      - run:
          name: Build Application
          command: dotnet build src/SampleApi/SampleApi.csproj --no-restore

      - run:
          name: Run Unit Tests
          command: dotnet test tests/SampleApi.Tests/SampleApi.Tests.csproj --no-build

workflows:
  version: 2

  build:
    jobs:
      - build
